export default [
    {
        "id": "1",
        "city": "Minsk",
        "title": "Rublevsky",
        "type": "food" as const,
        "openingTime": "09:00",
        "closingTime": "21:00",
        "distance": 0,
        "description": "Santa Retail was founded in 1995 and is part of the Santa group of companies. Today we are a large national chain of stories of various formats: markets, supermarkets and convenience stores.",
        "image": "https://photo.virtualbrest.by/uploads/2017/02/04/i11.jpg",
        "lat": 50,
        "lon": 27.7
    },
    {
        "id": "2",
        "city": "Minsk",
        "title": "Rublevsky",
        "type": "food" as const,
        "openingTime": "09:00",
        "closingTime": "21:00",
        "distance": 0,
        "description": "Santa Retail was founded in 1995 and is part of the Santa group of companies. Today we are a large national chain of stories of various formats: markets, supermarkets and convenience stores.",
        "image": "https://lh3.googleusercontent.com/proxy/qfzHyBhSKpq6XMIl2FNvBEuI4Tf9V_DdV8R1fJVWp5yNcsK39iAUWmcIKIR5HgaUpH2ec4LAZzX_n3UtlPU",
        "lat": 51.7,
        "lon": 27.3
    },
    {
        "id": "3",
        "city": "Minsk",
        "title": "Rublevsky",
        "type": "food" as const,
        "openingTime": "09:00",
        "closingTime": "21:00",
        "distance": 0,
        "description": "Santa Retail was founded in 1995 and is part of the Santa group of companies. Today we are a large national chain of stories of various formats: markets, supermarkets and convenience stores.",
        "image": "https://blizko.by/ckeditor_assets/pictures/51676/content_1.jpg",
        "lat": 52.5,
        "lon": 28.5
    },
    {
        "id": "4",
        "city": "Minsk",
        "title": "Rublevsky",
        "type": "food" as const,
        "openingTime": "09:00",
        "closingTime": "21:00",
        "distance": 0,
        "description": "Santa Retail was founded in 1995 and is part of the Santa group of companies. Today we are a large national chain of stories of various formats: markets, supermarkets and convenience stores.",
        "image": "https://photo.brestcity.com/2017/rublevskiy_brestcity01.jpg",
        "lat": 54,
        "lon": 28.1
    },
    {
        "id": "5",
        "city": "Minsk",
        "title": "Rublevsky",
        "type": "food" as const,
        "openingTime": "09:00",
        "closingTime": "21:00",
        "distance": 0,
        "description": "Santa Retail was founded in 1995 and is part of the Santa group of companies. Today we are a large national chain of stories of various formats: markets, supermarkets and convenience stores.",
        "image": "https://vitebsk.biz/source/photos/2019/09/13/20190909-132433-kopiya.jpg",
        "lat": 52.3,
        "lon": 27.1
    },
    {
        "id": "6",
        "city": "Minsk",
        "title": "Sportmaster",
        "type": "sport" as const,
        "openingTime": "08:00",
        "closingTime": "20:00",
        "distance": 0,
        "description": "We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.",
        "image": "https://pogovorim.by/uploads/posts/2017-09/1505556040_5.jpg",
        "lat": 55.5,
        "lon": 26
    },
    {
        "id": "7",
        "city": "Minsk",
        "title": "Sportmaster",
        "type": "sport" as const,
        "openingTime": "08:00",
        "closingTime": "20:00",
        "distance": 0,
        "description": "We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.",
        "image": "https://triniti-grodno.by/assets/images/3-etazh/sportmaster/1a31e25b-7036-47dd-8714-5a79d63defe8.jpeg",
        "lat": 53.3,
        "lon": 26.5
    },
    {
        "id": "8",
        "city": "Minsk",
        "title": "Sportmaster",
        "type": "sport" as const,
        "openingTime": "08:00",
        "closingTime": "20:00",
        "distance": 0,
        "description": "We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.",
        "image": "https://www.shoes-report.ru/upload/iblock/383/sportmaster_gotovitsya_k_vykhodu_na_rynok_evropy.jpg",
        "lat": 51.1,
        "lon": 26.9
    },
    {
        "id": "9",
        "city": "Minsk",
        "title": "Sportmaster",
        "type": "sport" as const,
        "openingTime": "08:00",
        "closingTime": "20:00",
        "distance": 0,
        "description": "We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.",
        "image": "https://ru.hrodna.life/wp-content/uploads/2020/02/sportmaster-grodno-01-1024x512.png",
        "lat": 50.1,
        "lon": 28.8
    },
    {
        "id": "10",
        "city": "Minsk",
        "title": "Sportmaster",
        "type": "sport" as const,
        "openingTime": "08:00",
        "closingTime": "20:00",
        "distance": 0,
        "description": "We are a sports store for the whole family! Everything for sports and outdoor activities - from the simplest sporting goods to the latest generation of technological equipment.",
        "image": "https://rau.ua/wp-content/uploads/2019/08/Foto_SPORTMASTER-810x528.jpg",
        "lat": 56.3,
        "lon": 25.8
    },
    {
        "id": "11",
        "city": "Minsk",
        "title": "Korona",
        "type": "food/non-food" as const,
        "openingTime": "10:00",
        "closingTime": "22:00",
        "distance": 0,
        "description": "The first shopping center 'Korona' was opened on August 15, 2006 in Minsk at 24 Kalvariyskaya Street.",
        "image": "https://kolodischi.by/piximage/resize/684x*/storage/uploaded/eef04fed203ba9d11e9d1817dad80701.jpg",
        "lat": 54.4,
        "lon": 27.2
    },
    {
        "id": "12",
        "city": "Minsk",
        "title": "Korona",
        "type": "food/non-food" as const,
        "openingTime": "10:00",
        "closingTime": "22:00",
        "distance": 0,
        "description": "The first shopping center 'Korona' was opened on August 15, 2006 in Minsk at 24 Kalvariyskaya Street.",
        "image": "https://photo.virtualbrest.by/uploads/2016/01/21/t32.jpg",
        "lat": 50,
        "lon": 26.1
    },
    {
        "id": "13",
        "city": "Minsk",
        "title": "Korona",
        "type": "food/non-food" as const,
        "openingTime": "10:00",
        "closingTime": "22:00",
        "distance": 0,
        "description": "The first shopping center 'Korona' was opened on August 15, 2006 in Minsk at 24 Kalvariyskaya Street.",
        "image": "https://content.onliner.by/news/2015/10/default/fa8c0acca51246cfbee5ddc9fa244a77.jpg",
        "lat": 53.2,
        "lon": 27.6
    },
    {
        "id": "14",
        "city": "Minsk",
        "title": "Korona",
        "type": "food/non-food" as const,
        "openingTime": "10:00",
        "closingTime": "22:00",
        "distance": 0,
        "description": "The first shopping center 'Korona' was opened on August 15, 2006 in Minsk at 24 Kalvariyskaya Street.",
        "image": "https://img.tyt.by/n/regiony/05/10/korona1.jpg",
        "lat": 52.1,
        "lon": 28
    },
    {
        "id": "15",
        "city": "Minsk",
        "title": "Korona",
        "type": "food/non-food" as const,
        "openingTime": "10:00",
        "closingTime": "22:00",
        "distance": 0,
        "description": "The first shopping center 'Korona' was opened on August 15, 2006 in Minsk at 24 Kalvariyskaya Street.",
        "image": "https://www.belta.by/images/storage/news/with_archive/2018/000022_1544424579_328674_big.jpg",
        "lat": 53.9,
        "lon": 28.5
    },
];
